<?php
namespace Kily\Tools1C\Tests\ClientBankExchange;

use Kily\Tools1C\ClientBankExchange\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-10 at 17:43:47.
 */
class ExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Kily\Tools1C\ClientBankExchange\Exception::__construct
     */
    public function test__construct() {
        $e = new Exception('some str with {{replace}}',['{{replace}}'=>'number 1']);
        $this->assertEquals('some str with number 1',$e->getMessage());
    }
}
