<?php

namespace Tests\Kily\Tools1C\Tests\ClientBankExchange;

use Kily\Tools1C\ClientBankExchange\Exception;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-10 at 17:43:47.
 */
class ExceptionTest extends TestCase
{
    /**
     * @covers Kily\Tools1C\ClientBankExchange\Exception::__construct
     */
    public function test__construct()
    {
        $e = new Exception('some str with {{replace}}', ['{{replace}}' => 'number 1']);
        $this->assertEquals('some str with number 1', $e->getMessage());
    }
}
